### ISSUE TITLE
 dyld[50013]: missing symbol called

### ISSUE THREAD

**Issue by Hoozia** [Atome-FE/llama-node#21]
```

import { LLama } from "llama-node";
import { LLamaCpp, LoadConfig } from "llama-node/dist/llm/llama-cpp.js";


const model = path.resolve(process.cwd(), "./src/ggml-vicuna-13b-1.1-q4_0.bin");


const llama = new LLama(LLamaCpp);

const config: LoadConfig = {
    path: model,
    enableLogging: true,
    nCtx: 1024,
    nParts: -1,
    seed: 0,
    f16Kv: false,
    logitsAll: false,
    vocabOnly: false,
    useMlock: false,
    embedding: false,
};

llama.load(config);

const template = `How are you`;

const prompt = `### Human:

${template}

### Assistant:`;

llama.createCompletion(
    {
        nThreads: 4,
        nTokPredict: 2048,
        topK: 40,
        topP: 0.1,
        temp: 0.2,
        repeatPenalty: 1,
        stopSequence: "### Human",
        prompt,
    },
    (response) => {
        process.stdout.write(response.token);
    }
);

```

My code was written 

dyld[50013]: missing symbol called
sh: line 1: 50013 Abort trap: 6 node dist/app.js

I am getting an error, what is the reason and what is the solution?

**Comment by Hoozia** [comment]
my os : apple m1

**Comment by hlhr202** [comment]
Hi, can try upgrade to llama-node@0.0.26? Also make sure your nodejs >= 16

**Comment by Hoozia** [comment]
Yes, I proceeded with both the package version and node version as you said, but the same error occurs.

```
node --version
v18.16.0


package.json
    "@llama-node/core": "^0.0.26",
    "@llama-node/llama-cpp": "^0.0.26",
```

**Comment by hlhr202** [comment]
![image](https://user-images.githubusercontent.com/2355528/232476626-eea17a93-1ce3-4924-af88-2edf7e83e9bb.png)
@Hoozia I have checked very carefully, I am using llama-node with @llama-node/llama-cpp, both versions are 0.0.26, and I ran it in Apple Silicon. The screenshot can prove the architecture and version I have used, everything just worked fine. Could you try reinstall your npm packages, better remove all node_modules before installation and try it again?

**Comment by Hoozia** [comment]
Thank you for your confirmation. I also checked my version,
```
22.4.0 Darwin Kernel Version 22.4.0: Mon Mar 6 21:00:41 PST 2023; It comes out as root:xnu-8796.101.5~3/RELEASE_ARM64_T8103 arm64 .
``` 

Is there a problem with the kernel version being 22.4.0?

**Comment by hlhr202** [comment]
@Hoozia I dont think so. can you check if the version of llama-cpp package.json in your node_modules?
If anything is aligned, I will probably provide a way for self compiled binary.

**Comment by Hoozia** [comment]
```
{
  "name": "@llama-node/llama-cpp",
  "version": "0.0.26",
  "main": "index.js",
  "types": "index.d.ts",
  "napi": {
    "name": "@llama-node/llama-cpp",
    "triples": {
      "additional": [
        "aarch64-apple-darwin",
        "aarch64-linux-android",
        "aarch64-unknown-linux-gnu"
      ]
    }
  },
  "license": "MIT",
  "devDependencies": {},
  "ava": {
    "timeout": "3m"
  },
  "engines": {
    "node": ">= 10"
  },
  "scripts": {
    "prepublish": "npm run artifacts",
    "cross-compile": "rimraf @llama-node && tsx scripts/cross-compile.ts",
    "artifacts": "tsx scripts/artifacts.ts",
    "build": "napi build --platform --release",
    "build:debug": "napi build --platform",
    "test": "vitest",
    "start": "tsx example/load.ts",
    "embedding": "tsx example/embedding.ts",
    "inference": "tsx example/inference.ts",
    "tokenize": "tsx example/tokenize.ts",
    "semantic-compare": "tsx example/semantic-compare/compare.ts",
    "universal": "napi universal",
    "version": "napi version"
  },
  "repository": {
    "url": "https://github.com/hlhr202/llama-node"
  },
  "homepage": "https://github.com/hlhr202/llama-node"
}
```
@hlhr202 
here, my local @llama-node/llama-cpp package.json

**Comment by hlhr202** [comment]
thats strange. ok I will provide a way for self compilation. just give me some time. thanks.

**Comment by Hoozia** [comment]
ok thank you for your time

**Comment by Hoozia** [comment]
I deleted node_modules and installed the package again, but the same error occurred. If you are modifying the source a lot because of me, it is okay not to modify it. sorry...

**Comment by Hoozia** [comment]
oh thank you so much it works fine!
