### ISSUE TITLE
llama-node does not display prompt in Deno environment

### ISSUE THREAD

**Issue by KiraCoding** [Atome-FE/llama-node#23]
I am currently trying to use the `llama-node@0.0.28` library with [Deno](https://deno.land). However, when I execute my program, I am not getting the expected prompt result. Instead, the Rust backend is returning `Ok(())`. I am suspecting that the issue might be related to a compatibility problem between `llama-node@0.0.28` and the [Deno](https://deno.land) runtime environment or am I missing something?

Any help or guidance on how to resolve this issue would be greatly appreciated. Thank you in advance for your assistance.

- **Lllama-node:** `llama-node@0.0.28`
- **Runtime:** `deno 1.32.5`
- **Model:** `ggml-model-q4_0.bin` / `7B alpaca 4bit quantized` (Ran flawless with `llama-rs` itself)

### `main.ts` code:
```ts
import { resolve } from "https://deno.land/std@0.184.0/path/mod.ts";
import { LLama } from "npm:llama-node@0.0.28";
import { LLamaRS } from "npm:llama-node@0.0.28/dist/llm/llama-rs.js";

const llama = new LLama(LLamaRS);

llama.load({
  path: resolve(Deno.cwd(), "./models/7B/ggml-model-q4_0.bin"),
});

const template = `How are you?`;

const prompt = `### Human:

${template}

### Assistant:`;

llama.createCompletion(
  {
      prompt,
      numPredict: 128,
      temp: 0.2,
      topP: 1,
      topK: 40,
      repeatPenalty: 1,
      repeatLastN: 64,
      seed: 0,
      feedPrompt: true,
  },
  (response) => {
      console.log(response.token)
  }
);
```

### `console.log` output:
```
DEBUG RS - deno_runtime::worker:418 - received module evaluate Ok(
    Ok(
        (),
    ),
)
```

**Comment by hlhr202** [comment]
@KiraCoding Deno FFI has different implementation compared to node native api. There is no plan for supporting Deno in short term.
Also this issue is pending https://github.com/napi-rs/napi-rs/issues/900

**Comment by KiraCoding** [comment]
Alright acknowledged.
