### ISSUE TITLE
Expand on install/usage instructions

### ISSUE THREAD

**Issue by bakman2** [Atome-FE/llama-node#26]
readme states, install:

`npm install llama-node`
and provides some usage examples, which don't actually work, it is typescript, so there are more requirements.

Please provide all prerequisite installation instructions that actually provides a working example.  

It might all be second nature to experts, but for the less fortunate it is not as straight forward. (ie. don't redirect someone to some examples directory with a config file as that still requires prerequisite steps).

**Comment by hlhr202** [comment]
@bakman2 Thanks for your feedback. will maintain more examples for pure javascript.

**Comment by hlhr202** [comment]
served a doc site here. https://llama-node.vercel.app/docs/start
provide pure javascript(ES Module) examples. (But be careful about the es module type)
