### ISSUE TITLE
Failed to load modal

### ISSUE THREAD

**Issue by Bazhan4ik** [Atome-FE/llama-node#32]
```
llama.cpp: loading model from C:/Users/bazha/work/ai/models/llama/ggml-vic13b-uncensored-q8_0.bin
error loading model: unrecognized tensor type 8

llama_init_from_file: failed to load model
[2023-04-28T12:32:46Z INFO  llama_node_cpp::context] AVX = 1 | AVX2 = 1 | AVX512 = 0 | AVX512_VBMI = 0 | AVX512_VNNI = 0 | FMA = 1 | NEON = 0 | ARM_FMA = 0 | F16C = 1 | FP16_VA = 0 | WASM_SIMD = 0 | BLAS = 0 | SSE3 = 1 | VSX = 0 |
[2023-04-28T12:32:46Z INFO  llama_node_cpp::llama] tokenized_stop_prompt: None
```

here the code, i just copied from the website:
```
import { LLM } from "llama-node";
import { LLamaCpp } from "llama-node/dist/llm/llama-cpp.js";
import path from "path";

const model = "C:/Users/bazha/work/ai/models/llama/ggml-vic13b-uncensored-q8_0.bin"
const llama = new LLM(LLamaCpp);
const config = {
    path: model,
    enableLogging: true,
    nCtx: 1024,
    nParts: -1,
    seed: 0,
    f16Kv: false,
    logitsAll: false,
    vocabOnly: false,
    useMlock: false,
    embedding: false,
    useMmap: true,
};
llama.load(config);

const template = `How are you?`;
const prompt = `A chat between a user and an assistant. USER: ${template}; ASSISTANT:`;

llama.createCompletion({
    nThreads: 4,
    nTokPredict: 2048,
    topK: 40,
    topP: 0.1,
    temp: 0.2,
    repeatPenalty: 1,
    prompt,
}, (response) => {
    process.stdout.write(response.token);
});
```

node: v18.12.1
@llama-node/llama-cpp: ^0.0.31
llama-node: ^0.0.31

[model i downloaded](https://huggingface.co/eachadea/ggml-vicuna-13b-1.1/blob/main/ggml-vic13b-uncensored-q8_0.bin)

**Comment by hlhr202** [comment]
@Bazhan4ik this should be related to llama.cpp model update. the llama-node can not always sync to the latest llama.cpp
can you give some hint that whether this can be load on latest llama.cpp. I mean sometimes even some newest model can just be produced with new tensor type but not always be able to be load on llama.cpp.
if the latest llama.cpp can load, then I will just do a simple upgrade

**Comment by Bazhan4ik** [comment]
Yes, I installed uncensored q8 from [this list](https://huggingface.co/eachadea/ggml-vicuna-13b-1.1/tree/main), which, I guess, is the newest. Then I installed q4 and it worked.

**Comment by hlhr202** [comment]
> Yes, I installed uncensored q8 from [this list](https://huggingface.co/eachadea/ggml-vicuna-13b-1.1/tree/main), which, I guess, is the newest. Then I installed q4 and it worked.

give me a few minutes and I just try upgrade with latest llama.cpp then you try if it can be solved thx

**Comment by hlhr202** [comment]
@Bazhan4ik please try upgrade both llama-node and @llama-node/llama-cpp to 0.0.32
![image](https://user-images.githubusercontent.com/2355528/235191589-f3e3a506-06ce-47a4-a2ab-01c94330bdf2.png)

**Comment by Bazhan4ik** [comment]
works now!
![image](https://user-images.githubusercontent.com/70026195/235192646-9dccaa7e-da52-432c-93b9-62d42d098a79.png)
