### ISSUE TITLE
@llama-node/rwkv-cpp only contains rwkv-cpp.darwin-arm64.node

### ISSUE THREAD

**Issue by yorkzero831** [Atome-FE/llama-node#44]
https://www.npmjs.com/package/@llama-node/rwkv-cpp?activeTab=code

**Comment by yorkzero831** [comment]
@hlhr202  
got such error when manually copy rwkv-cpp.win32-x64-msvc.node into dependecies
```
Process finished with exit code -1073741819 (0xC0000005)
```

**Comment by hlhr202** [comment]
> @hlhr202 got such error when manually copy rwkv-cpp.win32-x64-msvc.node into dependencies
> 
> ```
> Process finished with exit code -1073741819 (0xC0000005)
> ```

just give me some time, fixing this.

**Comment by yorkzero831** [comment]
@hlhr202 
No worry, you are always so cool

**Comment by hlhr202** [comment]
> > @hlhr202 got such error when manually copy rwkv-cpp.win32-x64-msvc.node into dependencies
> > ```
> > Process finished with exit code -1073741819 (0xC0000005)
> > ```
> 
> just give me some time, fixing this.

emmm, so this means you have compiled successfully on windows but cannot run it?

**Comment by hlhr202** [comment]
ok got this, will figure out what's wrong with win build.
I can load the model and tokenizer, but failed while doing inference.

**Comment by yorkzero831** [comment]
> ok got this, will figure out what's wrong with win build. I can load the model and tokenizer, but failed while doing inference.
seems like the problem happens because pointer passing between rust and rwkv

**Comment by yorkzero831** [comment]
@hlhr202 
I have done some dirty changes, it works on my windows pc, and I found the end_token in rwkv-raven v11 looks like 187 so I set it as default 
https://github.com/yorkzero831/llama-node/commit/72413be2964ed6b24fb5e425893d845d0aeb5ad0

**Comment by yorkzero831** [comment]
the log will look like
```
[2023-05-05T17:28:24Z INFO  rwkv_node_cpp::context] AVX = 1 | AVX2 = 1 | AVX512 = 0 | FMA = 1 | NEON = 0 | ARM_FMA = 0 | F16C = 1 | FP16_VA = 0 | WASM_SIMD = 0 | BLAS = 0 | SSE3 = 1 | VSX = 0 | 
1
token: 1533
 world

token: 15
.

token: 187

test test1 ... ok
```

**Comment by hlhr202** [comment]
> 

@yorkzero831 awesome. would you mind create pr for this? we warmly welcome contribution.

**Comment by yorkzero831** [comment]
@hlhr202 sure working on it

**Comment by yorkzero831** [comment]
@hlhr202  could you please have a look at this https://github.com/Atome-FE/llama-node/pull/46
