### ISSUE TITLE
How to use the GPU?

### ISSUE THREAD

**Issue by dev-bre** [Atome-FE/llama-node#50]
Hi, I am looking for a way for this library to trigger the inference generation using the GPU. 
Is this supported?

**Comment by dev-bre** [comment]
thanks for the reply. do you have an idea when you can provide some docs? I think having this lib to work on the gpu is wjhat would make it super useful. cpu processing is quite slow compared to gpu.

**Comment by hlhr202** [comment]
emm, I think we have to wait a while. llama.cpp have not implement a full GPU inference yet for now.
https://github.com/ggerganov/llama.cpp/discussions/1220

**Comment by dev-bre** [comment]
Thanks for the reply! Hopefully they will add support at some point. Once it's done, do you think it would be easy to expose in this library?

**Comment by hlhr202** [comment]
> Thanks for the reply! Hopefully they will add support at some point. Once it's done, do you think it would be easy to expose in this library?

not easy. the reason is that i have to keep compatibility for several platforms. additionally cuda is depending on nvcc which introduce a lot of complex in compiling and linking.

**Comment by dev-bre** [comment]
Looks like GPU support is coming sooner than expected!

https://www.reddit.com/r/LocalLLaMA/comments/13cpwpi/proof_of_concept_gpuaccelerated_token_generation/?utm_source=share&utm_medium=android_app&utm_name=androidcss&utm_term=1&utm_content=share_button

The guy raised an MR to the repo and he expect this to be in master within 4 weeks.

**Comment by dev-bre** [comment]
https://www.reddit.com/r/LocalLLaMA/comments/13gok03/llamacpp_now_officially_supports_gpu_acceleration/?utm_source=share&utm_medium=android_app&utm_name=androidcss&utm_term=1&utm_content=share_button

Llama-cpp Officially supports GPU generation! Do you have a plan on when to add this?
I think it would be really important for this lib!

**Comment by hlhr202** [comment]
> https://www.reddit.com/r/LocalLLaMA/comments/13gok03/llamacpp_now_officially_supports_gpu_acceleration/?utm_source=share&utm_medium=android_app&utm_name=androidcss&utm_term=1&utm_content=share_button
> 
> Llama-cpp Officially supports GPU generation! Do you have a plan on when to add this? I think it would be really important for this lib!

I will review this soon. hopefully they solve the static linking problem. otherwise llama-node users have to manually compile llama.cpp binary.

**Comment by dev-bre** [comment]
Thanks for this. If it comes to compiling it manually, I think it would be worth it adding some kind of readme for this. Like a step by step guide for win/Mac/Linux. This stuff can be tricky to build.

**Comment by hlhr202** [comment]
> Thanks for this. If it comes to compiling it manually, I think it would be worth it adding some kind of readme for this. Like a step by step guide for win/Mac/Linux. This stuff can be tricky to build.

sure thing.

**Comment by ralyodio** [comment]
....it sounds like from that thread that gpu rendering is something brand new, so it isn't requiring a gpu. this goes back to my original question why would it be fast on my laptop but slow on my server?

**Comment by hlhr202** [comment]
> ....it sounds like from that thread that gpu rendering is something brand new, so it isn't requiring a gpu. this goes back to my original question why would it be fast on my laptop but slow on my server?

@ralyodio is that both your laptop and server are using CPU right now?

**Comment by hlhr202** [comment]
The inference speed is pretty much depends on what kind of architecture you are using. basically, if you used M1/M2 mac book CPU, they might be a little bit faster than a consumer level x86 CPU.
the current build supported AVX2 in x86_64 and NEON+Apple Acceleration Framework in Arm Mac.
Could you check how is your CPU architecture and usage on your laptop and server?

**Comment by ralyodio** [comment]
The laptop is an intel i7 I think. The serve is a 32 core i5 I believe.

**Comment by ralyodio** [comment]
Intel Corporation Xeon E7 v3/Xeon E5 v3/Core  this is the server. its 32 cores.

that should be much faster than a laptop shouldn't it?

**Comment by hlhr202** [comment]
> 

I m not a pro on this. but the public resources show that FLOPS of 12th Gen i7-12700H (2022 published Alder Lake) is much higher than E5-2680 v3 (2014 published Haswell)
