### ISSUE TITLE
Unable to load latest GGML models using llama.cpp after latest quantisation changes

### ISSUE THREAD

**Issue by dev-bre** [Atome-FE/llama-node#60]
Following this commit on llama.cpp repo, https://github.com/ggerganov/llama.cpp/commit/b9fd7eee57df101d4a3e3eabc9fd6c2cb13c9ca1 any model which has been re-quantised, won't be loaded by the current version of llama-cpp shipped with this labrary.

What's the plan on updating llama-cpp to the latest available version?

**Comment by hlhr202** [comment]
> Following this commit on llama.cpp repo, [ggerganov/llama.cpp@b9fd7ee](https://github.com/ggerganov/llama.cpp/commit/b9fd7eee57df101d4a3e3eabc9fd6c2cb13c9ca1) any model which has been re-quantised, won't be loaded by the current version of llama-cpp shipped with this labrary.
> 
> What's the plan on updating llama-cpp to the latest available version?

yea probably within few days.

**Comment by hlhr202** [comment]
@dev-bre q5_1 is supported for llama.cpp backend

**Comment by HolmesDomain** [comment]
Does this work for Llama 2 as well? (q5_1)
